package catvet.entity;

public enum Breed {
	ABYSSINIAN, AEGEAN, AMERICAN_BOBTAIL, AMERICAN_CURL, AMERICAN_LONGHAIR, AMERICAN_SHORTHAIR,
	BENGAL, BIRMAN, BOMBAY, BRITISH_LONGHAIR, BRITISH_SHORTHAIR, BURMESE, CORNISH_REX, DOMESTIC_LONGHAIR, 
	DOMESTIC_SHORTHAIR, EGYPTIAN_MAU, JAPANESE_BOBTAIL,  MAINE_COON, NEBELUNG, ORIENTAL_LONGHAIR,
	ORIENTAL_SHORTHAIR, PERSIAN, RAGDOLL, RUSSIAN_BLUE, SAVANNAH, SIAMESE, SIBERIAN, 
	SCOTTISH_FOLD, SOMALI, SPHYNX, MIXED;
	
//	public static Breed getByName(String name) {
//		try {
//			return valueOf(name.toUpperCase());
//		} catch (IllegalArgumentException e) {
//			return MIXED;
//		}
//	}
}
